### PR TITLE
Finish support for iPad 2 devices

### PR DESCRIPTION
**Pull request by 270899colin**
This pull request adds the final offsets for the following devices on 9.2-9.3.4:

iPad2,1
iPad2,2
iPad2,3
iPad2,4

Note:
1. Kernelcache keys for iPad2,4 are missing, I had to assume the offsets were the same as the other iPads.
2. Most of these devices aren't tested, its possible that I made a typo somewhere or something is incorrect.

### CODE REVIEW

**Comment by benjamin-42** [comment]
@270899colin tested on at least one device? could you also resolve conflicts please? :) (they appeared with latest merge)

**Comment by 270899colin** [comment]
I tested it on one device and it works but now something went wrong with resolving the conflicts so I'm gonna check to see what went wrong.

**Comment by 270899colin** [comment]
No idea how to fix, gonna try refork

**Comment by leoyangtaiwan** [comment]
@270899cilin could u help to compile IPA for IPad2 9.2.1?

**Pull request closed without merging**
